//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proxy.Library.SOAPLibrary {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/Model.Library")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublishingHouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorName {
            get {
                return this.AuthorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorNameField, value) != true)) {
                    this.AuthorNameField = value;
                    this.RaisePropertyChanged("AuthorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorSurname {
            get {
                return this.AuthorSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorSurnameField, value) != true)) {
                    this.AuthorSurnameField = value;
                    this.RaisePropertyChanged("AuthorSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublishingHouse {
            get {
                return this.PublishingHouseField;
            }
            set {
                if ((object.ReferenceEquals(this.PublishingHouseField, value) != true)) {
                    this.PublishingHouseField = value;
                    this.RaisePropertyChanged("PublishingHouse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model.Library")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proxy.Library.SOAPLibrary.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proxy.Library.SOAPLibrary.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/Model.Library")]
    public enum Role : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StandardUser = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPLibrary.IServiceLibrary")]
    public interface IServiceLibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/Login", ReplyAction="http://tempuri.org/IServiceLibrary/LoginResponse")]
        BusinessLogic.Library.ViewModels.UserViewModel Login(BusinessLogic.Library.ViewModels.LoginViewModel loginVM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/AddBook", ReplyAction="http://tempuri.org/IServiceLibrary/AddBookResponse")]
        Proxy.Library.SOAPLibrary.Book AddBook(BusinessLogic.Library.BookViewModel book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/SearchBook", ReplyAction="http://tempuri.org/IServiceLibrary/SearchBookResponse")]
        System.Collections.Generic.List<BusinessLogic.Library.BookViewModel> SearchBook(BusinessLogic.Library.VieModels.SearchBookViewModel book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/UpdateBook", ReplyAction="http://tempuri.org/IServiceLibrary/UpdateBookResponse")]
        BusinessLogic.Library.BookViewModel UpdateBook(BusinessLogic.Library.BookViewModel bookToSearch, BusinessLogic.Library.BookViewModel bookWithNewValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/DeleteBook", ReplyAction="http://tempuri.org/IServiceLibrary/DeleteBookResponse")]
        bool DeleteBook(BusinessLogic.Library.BookViewModel book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/ReserveBook", ReplyAction="http://tempuri.org/IServiceLibrary/ReserveBookResponse")]
        BusinessLogic.Library.ReservationViewModel ReserveBook(BusinessLogic.Library.Mappers.BookWithAvailabilityVM book, BusinessLogic.Library.ViewModels.UserViewModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/ReturnBook", ReplyAction="http://tempuri.org/IServiceLibrary/ReturnBookResponse")]
        bool ReturnBook(int bookId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/GetReservationHistoryForAdmin", ReplyAction="http://tempuri.org/IServiceLibrary/GetReservationHistoryForAdminResponse")]
        System.Collections.Generic.List<BusinessLogic.Library.ReservationViewModel> GetReservationHistoryForAdmin(BusinessLogic.Library.ViewModels.UserViewModel userViewModel, BusinessLogic.Library.VieModels.SearchBookViewModel bookToReserve, System.Nullable<BusinessLogic.Library.Entities.ReservationStatus> reservationStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/GetReservationsHistoryForStandardUser", ReplyAction="http://tempuri.org/IServiceLibrary/GetReservationsHistoryForStandardUserResponse")]
        System.Collections.Generic.List<BusinessLogic.Library.ReservationViewModel> GetReservationsHistoryForStandardUser(BusinessLogic.Library.VieModels.SearchBookViewModel bookToReserve, BusinessLogic.Library.Entities.ReservationStatus reservationStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/SearchBookWithAvailabilityInfos", ReplyAction="http://tempuri.org/IServiceLibrary/SearchBookWithAvailabilityInfosResponse")]
        BusinessLogic.Library.Mappers.BookWithAvailabilityVM SearchBookWithAvailabilityInfos(BusinessLogic.Library.BookViewModel book);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLibraryChannel : Proxy.Library.SOAPLibrary.IServiceLibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLibraryClient : System.ServiceModel.ClientBase<Proxy.Library.SOAPLibrary.IServiceLibrary>, Proxy.Library.SOAPLibrary.IServiceLibrary {
        
        public ServiceLibraryClient() {
        }
        
        public ServiceLibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BusinessLogic.Library.ViewModels.UserViewModel Login(BusinessLogic.Library.ViewModels.LoginViewModel loginVM) {
            return base.Channel.Login(loginVM);
        }
        
        public Proxy.Library.SOAPLibrary.Book AddBook(BusinessLogic.Library.BookViewModel book) {
            return base.Channel.AddBook(book);
        }
        
        public System.Collections.Generic.List<BusinessLogic.Library.BookViewModel> SearchBook(BusinessLogic.Library.VieModels.SearchBookViewModel book) {
            return base.Channel.SearchBook(book);
        }
        
        public BusinessLogic.Library.BookViewModel UpdateBook(BusinessLogic.Library.BookViewModel bookToSearch, BusinessLogic.Library.BookViewModel bookWithNewValues) {
            return base.Channel.UpdateBook(bookToSearch, bookWithNewValues);
        }
        
        public bool DeleteBook(BusinessLogic.Library.BookViewModel book) {
            return base.Channel.DeleteBook(book);
        }
        
        public BusinessLogic.Library.ReservationViewModel ReserveBook(BusinessLogic.Library.Mappers.BookWithAvailabilityVM book, BusinessLogic.Library.ViewModels.UserViewModel user) {
            return base.Channel.ReserveBook(book, user);
        }
        
        public bool ReturnBook(int bookId, int userId) {
            return base.Channel.ReturnBook(bookId, userId);
        }
        
        public System.Collections.Generic.List<BusinessLogic.Library.ReservationViewModel> GetReservationHistoryForAdmin(BusinessLogic.Library.ViewModels.UserViewModel userViewModel, BusinessLogic.Library.VieModels.SearchBookViewModel bookToReserve, System.Nullable<BusinessLogic.Library.Entities.ReservationStatus> reservationStatus) {
            return base.Channel.GetReservationHistoryForAdmin(userViewModel, bookToReserve, reservationStatus);
        }
        
        public System.Collections.Generic.List<BusinessLogic.Library.ReservationViewModel> GetReservationsHistoryForStandardUser(BusinessLogic.Library.VieModels.SearchBookViewModel bookToReserve, BusinessLogic.Library.Entities.ReservationStatus reservationStatus) {
            return base.Channel.GetReservationsHistoryForStandardUser(bookToReserve, reservationStatus);
        }
        
        public BusinessLogic.Library.Mappers.BookWithAvailabilityVM SearchBookWithAvailabilityInfos(BusinessLogic.Library.BookViewModel book) {
            return base.Channel.SearchBookWithAvailabilityInfos(book);
        }
    }
}
